# Generated by Django 3.2.4 on 2021-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
                ('fechanacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
