# Generated by Django 3.2.4 on 2021-07-10 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0002_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deposito', models.DateTimeField(auto_now_add=True)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_registro.cuenta')),
            ],
        ),
    ]
