# Generated by Django 3.2.4 on 2021-07-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0003_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
