# Generated by Django 3.2.4 on 2021-07-11 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0004_auto_20210710_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateTimeField(auto_now_add=True)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_registro.cuenta')),
            ],
        ),
    ]
